name: slack-notify

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
      
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r jobs-scraper/apple/requirements.txt 
       
      - name: Run diff tests
        uses: mathiasvr/command-output@v1
        id: run_tests
        with:
          run: csv-diff jobs-scraper/apple/Apple-Careers-All-cp.csv jobs-scraper/apple/Apple-Careers-All.csv --key=id
      
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: ${{ steps.run_tests.outputs.stdout }}
          SLACK_TITLE: Post Title
          SLACK_CHANNEL: jobs
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
