name: slack-notify

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
      
      - name: diffs
        run: |
          python -m pip install --upgrade pip
          pip install -r jobs-scraper/apple/requirements.txt 
        
      - name: Set output variables
        id: vars
        run: |
          echo ::set-output name=pr_title::"csv-diff jobs-scraper/apple/Apple-Careers-All-cp.csv jobs-scraper/apple/Apple-Careers-All.csv --key=id    "
        
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C047UAANP4J'
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ steps.vars.outputs.pr_title }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Run diff tests
        run: |
          echo "csv-diff jobs-scraper/apple/Apple-Careers-All-cp.csv jobs-scraper/apple/Apple-Careers-All.csv --key=id" >> $GITHUB_OUTPUT
        id: run_tests
      
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: ${{join(steps.run_tests.outputs.*, '\n')}}
          SLACK_TITLE: CI Test Suite
          SLACK_CHANNEL: jobs
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
