name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r jobs-scraper/apple/requirements.txt 

      - name: Oli Run tests
        run: /home/runner/.local/bin/csv-diff jobs-scraper/apple/Apple-Careers-All-cp.csv jobs-scraper/apple/Apple-Careers-All.csv --key=id >> $HOME/slack.msg

      - name: Oli Run tests
        run: cat $HOME/slack.msg

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        # if: ${{ steps.run_tests.outputs.stdout }} != ""
        env:
          SLACK_MESSAGE: $(cat HOME/slack.msg)
          SLACK_TITLE: Post Title
          SLACK_CHANNEL: jobs
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
